services:
  the-nexus:
    image: the-nexus:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-nexus-container
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./sqlite.db:/app/sqlite.db:rw
