services:
  the-nexus:
    image: the-nexus
    container_name: the-nexus-container
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RIOT_API_TOKEN=${RIOT_API_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
    volumes:
      - ./sqlite.db:/app/sqlite.db:rw
