name: Deploy production application

on:
  push:
    paths-ignore:
      - 'docker/**'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'shell.nix'
      - 'Makefile'
      - 'compose.yml'

    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: true
          tags: lblcs/the-nexus:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker compose on prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /lblcs/docker/the-nexus
            echo JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" > .env
            echo ORIGIN="${{ secrets.ORIGIN }}" >> .env
            echo USERS_DB_PATH="${{ secrets.USERS_DB_PATH }}" >> .env
            echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> .env
            echo NODE_ENV="${{ env.NODE_ENV }}" >> .env
            echo RIOT_API_TOKEN="${{ secrets.RIOT_API_TOKEN }}" >> .env
            docker compose down
            docker compose pull
            docker compose up -d
