name: Deploy production application

on:
  push:
    paths-ignore:
      - 'docker/**'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'shell.nix'
      - 'Makefile'
      - 'compose.yml'
      - 'gradlew'
      - 'gradlew.bat'
      - 'src/itest/**'
      - 'src/test/**'

    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          file: docker/Dockerfile
          tags: lblcs/dennys:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker compose on prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /lblcs/docker/dennys
            echo LBLCS_JDBC_URL="${{ secrets.LBLCS_JDBC_URL }}" > .env
            echo LBLCS_JDBC_PW="${{ secrets.LBLCS_JDBC_PW }}" >> .env
            echo RIOT_API_TOKEN="${{ secrets.RIOT_API_TOKEN }}" >> .env
            echo RIOT_USE_STUBS=False >> .env
            docker compose down
            docker compose pull
            docker compose up -d
            rm -f ./.env
