name: Deploy on Prod

on:
  push:
    branches: ['main']

jobs:
  env:
    uses: ./.github/workflows/build-env.yaml

  build:
    needs: env
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env

      - name: Import env
        shell: bash
        run: |
          while read env; do
            echo $env >> $GITHUB_ENV
          done <<< $(cat .env.art)

      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t lblcs/${{ env.APP }}:latest .
          docker tag lblcs/${{ env.APP }}:latest lblcs/${{ env.APP }}:${{ env.VERSION }}
          docker push lblcs/${{ env.APP }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env

      - name: Import env
        shell: bash
        run: |
          while read env; do
            echo $env >> $GITHUB_ENV
          done <<< $( cat .env.art)

      - name: Execute docker compose on prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd docker/lblcs/${{ env.APP }}
            echo POSTGRES_CONNECTION_URI="${{ secrets.POSTGRES_CONNECTION_URI }}" > .env
            echo RIOT_API_TOKEN="${{ secrets.RIOT_API_TOKEN }}" >> .env
            echo ORIGIN="${{ secrets.ORIGIN }}" >> .env
            echo JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" >> .env
            echo RIOT_PROVIDER_ID="${{ secrets.RIOT_PROVIDER_ID }}" >> .env
            docker-compose down
            docker-compose pull
            docker-compose up -d
